name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - master

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to S3
        run: |
          aws s3 sync . s3://${{ vars.S3_BUCKET_NAME }}/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

  deploy-hml:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment:
      name: hml

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to S3
        run: |
          aws s3 sync . s3://${{ vars.S3_BUCKET_NAME }}/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

  deploy-prd:
    runs-on: ubuntu-latest
    needs: [deploy-hml, deploy-dev]
    environment:
      name: prd

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to S3
        run: |
          aws s3 sync . s3://${{ vars.S3_BUCKET_NAME }}/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
